version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mplspsql
      POSTGRES_PASSWORD: mplspsql
      POSTGRES_DB: transactcomisdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
